# Generated by Django 3.0.3 on 2020-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='activity',
            new_name='activity_place',
        ),
        migrations.AddField(
            model_name='myuser',
            name='activity_type',
            field=models.CharField(choices=[('I', 'Institute'), ('W', 'Work')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
