# Generated by Django 3.0.3 on 2020-03-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionsapp', '0002_auto_20200304_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='questionsapp.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default=None, verbose_name='description'),
            preserve_default=False,
        ),
    ]
