# Generated by Django 3.0.3 on 2020-03-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsapp', '0003_auto_20200304_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
