# Generated by Django 3.0.3 on 2020-03-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsapp', '0006_auto_20200304_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
    ]
